spring:
  application:
    name: AirlineAPI
  app:
      jwtSecret: 7069234323782b5a5c345c6a692d2b753a652569693f6f4a2c71305d75
      jwtExpirationMs: 86400000
  ecom:
      app:
          jwtCookieName: jwtCookie
  datasource:
      url: jdbc:postgresql://localhost:5432/AirlineAPI
      username: postgres
      password: 123456789
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
          ddl-auto: update
    properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
    show-sql: true

frontend:
    url: http://localhost:3000
