spring:
  application:
    name: AirlineAPI
  app:
      jwtSecret: ${JWT_SECRET}
      jwtExpirationMs: ${JWT_EXPIRATION_MS}
  ecom:
      app:
          jwtCookieName: jwtCookie
  datasource:
      url: ${DATASOURCE_URL}
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
          ddl-auto: update
      properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect

frontend:
    url: ${FRONTEND_URL}
